# Generated by Django 4.2.6 on 2024-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_productsstores_initialprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsstores',
            name='ProductDescription',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='productsstores',
            name='ProductImageBackView',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProductsInventoryImages/', verbose_name='Back VieW Product Image'),
        ),
        migrations.AddField(
            model_name='productsstores',
            name='ProductImageFrontView',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProductsInventoryImages/', verbose_name='Front VieW Product Image'),
        ),
        migrations.AddField(
            model_name='productsstores',
            name='ProductImageLeftSideView',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProductsInventoryImages/', verbose_name='Left Side VieW Product Image'),
        ),
        migrations.AddField(
            model_name='productsstores',
            name='ProductImageRightSideView',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProductsInventoryImages/', verbose_name='Right Side VieW Product Image'),
        ),
        migrations.AlterField(
            model_name='productsstores',
            name='ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/ProductsInventoryImages/', verbose_name='Main Product Image'),
        ),
    ]
