# Generated by Django 4.2.6 on 2024-07-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_productsstores_productdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AinaZaKuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AinaYaKuku', models.CharField(max_length=100, verbose_name='Aina Ya Kuku')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aina Za Kuku',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaKuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 1 - KG ')),
                ('Protini', models.IntegerField(blank=True, null=True, verbose_name='Kiwango Cha Protini - % Kwenye 1Kg Ya Chakula')),
                ('Cabohydrate', models.IntegerField(blank=True, null=True, verbose_name='Kiwango Cha Cabohydrate- %')),
                ('Wanga', models.IntegerField(blank=True, null=True, verbose_name='Kiwango Cha Wanga- %')),
                ('Fati', models.IntegerField(blank=True, null=True, verbose_name='Kiwango Cha Fati- %')),
                ('Vitamini', models.IntegerField(blank=True, null=True, verbose_name='Kiwango Cha Vitamini- %')),
                ('KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 1 - KG (Usijaze)')),
                ('KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 1 - KG (Usijaze)')),
                ('KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 1 - KG (Usijaze)')),
                ('KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 1 - KG (Usijaze)')),
                ('KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_1', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 1 - KG (Usijaze)')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('AinaYaKuku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.ainazakuku', verbose_name='Aina Ya Kuku')),
            ],
            options={
                'verbose_name_plural': 'Taarifa Za Kuku',
            },
        ),
        migrations.CreateModel(
            name='UmriWaKuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UmriKwaWiki', models.IntegerField(verbose_name='Wiki ?')),
                ('UmriKwaSiku', models.IntegerField(blank=True, null=True, verbose_name='Siku ? (Usijaze)')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Umri Wa Kuku',
            },
        ),
        migrations.CreateModel(
            name='UnitZaVyakula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(max_length=500, verbose_name='Unit')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Unit Za Vyakula',
            },
        ),
        migrations.CreateModel(
            name='Virutubisho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protini', models.IntegerField(verbose_name='Kiwango Cha Protini- %')),
                ('Cabohydrate', models.IntegerField(verbose_name='Kiwango Cha Cabohydrate- %')),
                ('Wanga', models.IntegerField(verbose_name='Kiwango Cha Wanga- %')),
                ('Fati', models.IntegerField(verbose_name='Kiwango Cha Fati- %')),
                ('Vitamini', models.IntegerField(verbose_name='Kiwango Cha Vitamini- %')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Umri Wa Kuku',
            },
        ),
        migrations.CreateModel(
            name='Vyakula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Jina La Chakula')),
                ('ProductDescription', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Maelezo')),
                ('InitialPrice', models.IntegerField(blank=True, null=True, verbose_name='Bei Ya Mwanzo Ya Chakula')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Bei Ya sasa Ya Chakula (Usijaze)')),
                ('ProductQuantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Kiasi - KG (Usijaze)')),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='media/PichaZaVyakula/', verbose_name='Picha Ya Chakula')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.unitzavyakula', verbose_name='Unit Ya Chakula')),
            ],
            options={
                'verbose_name_plural': 'Vyakula',
            },
        ),
        migrations.DeleteModel(
            name='OurServices',
        ),
        migrations.RemoveField(
            model_name='productscart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productscartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productscartitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productscartitems',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productscategories',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='productscategories',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='productsorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productsorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsorderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productsorderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsorderitems',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsstores',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='productsstores',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='productsstores',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='productsstores',
            name='productCategory',
        ),
        migrations.DeleteModel(
            name='PeoplesCategories',
        ),
        migrations.DeleteModel(
            name='ProductsCart',
        ),
        migrations.DeleteModel(
            name='ProductsCartItems',
        ),
        migrations.DeleteModel(
            name='ProductsCategories',
        ),
        migrations.DeleteModel(
            name='ProductsFeatures',
        ),
        migrations.DeleteModel(
            name='ProductsOrder',
        ),
        migrations.DeleteModel(
            name='ProductsOrderItems',
        ),
        migrations.DeleteModel(
            name='ProductsStores',
        ),
        migrations.DeleteModel(
            name='ProductsUnit',
        ),
        migrations.AddField(
            model_name='virutubisho',
            name='JinaLaChakula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vyakula', verbose_name='Jina La Chakula'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='JinaLaChakula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vyakula', verbose_name='Jina La Chakula'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='UmriKwaWiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.umriwakuku', verbose_name='Umri Wa Kuku - Wiki ?'),
        ),
    ]
