# Generated by Django 4.2.6 on 2024-07-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_ainazakuku_taarifazakuku_umriwakuku_unitzavyakula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huduma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaHuduma', models.CharField(max_length=100, verbose_name='Jina La Huduma')),
                ('PichaYaHuduma', models.ImageField(blank=True, null=True, upload_to='media/PichaZaHuduma/', verbose_name='Picha Ya Huduma')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Huduma',
            },
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Cabohydrate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Cabohydrate- %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Fati',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Fati- %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 1 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 1 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 1 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 1 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 1 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Protini',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Protini - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Vitamini',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Vitamini- %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Wanga',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Wanga- %'),
        ),
        migrations.CreateModel(
            name='MgawanjoWaHuduma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaHuduma', models.CharField(max_length=100, verbose_name='Jina La Huduma')),
                ('PichaYaHuduma', models.ImageField(blank=True, null=True, upload_to='media/PichaZaHuduma/', verbose_name='Picha Ya Huduma')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.huduma', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Mgawanjo Wa Huduma',
            },
        ),
    ]
