# Generated by Django 4.2.6 on 2024-07-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_huduma_alter_taarifazakuku_cabohydrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 10 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 2 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 3 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 4 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 5 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 6 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 7 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 8 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 10 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 2 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 3 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 4 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 5 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 6 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 7 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 8 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki 9 - KG '),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 10 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 2 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 3 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 4 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 5 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 6 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 7 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 8 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 2 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 3 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 5 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 10 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 2 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 3 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 4 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 5 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 6 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 7 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 8 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 10 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 2 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 3 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 4 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 5 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 6 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 7 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 8 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 10 - KG (Usijaze)'),
        ),
    ]
