# Generated by Django 4.2.6 on 2024-07-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_taarifazakuku_kiasichacabohydratekilichopokwenye_kiasichachakulakwawiki_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VyakulaCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0, verbose_name='Jumla Ya Bei')),
                ('total_Kilos', models.FloatField(default=0, verbose_name='Jumla Ya Kilos')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vyakula  Cart',
            },
        ),
        migrations.CreateModel(
            name='VyakulaCartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vyakulacart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vyakula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vyakula  Cart Items',
            },
        ),
    ]
