# Generated by Django 4.2.6 on 2024-07-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_vyakulacart_vyakulacartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='VyakulaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Jumla Ya Bei')),
                ('total_Kilos', models.FloatField(verbose_name='Jumla Ya Kilos')),
                ('Customer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imewekwa Na:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vyakulacart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vyakula Orders',
            },
        ),
        migrations.CreateModel(
            name='VyakulaOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vyakulaorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vyakula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vyakula Orders Items',
            },
        ),
    ]
