# Generated by Django 4.2.6 on 2024-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_vyakulaorder_vyakulaorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Cabohydrate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Cabohydrate- % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Fati',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Fati- % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Vitamini',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Vitamini- % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='Wanga',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Wanga- % Kwenye 1Kg Ya Chakula'),
        ),
    ]
