# Generated by Django 4.2.6 on 2024-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_taarifazakuku_cabohydrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCabohydrateKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Cabohydrate Kwa Wiki 9 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFatiKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Fati Kwa Wiki 9 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 10 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 4 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 6 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 7 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 8 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 9 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaVitaminiKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Vitamini Kwa Wiki 9 - KG (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki 9 - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaProtiniKilichopokwenye_KiasiChaChakulaKwaWiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Protini Kwa Wiki 1 - KG (Usijaze)'),
        ),
    ]
