# Generated by Django 4.2.6 on 2024-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_taarifazakuku_kiasichacabohydratekilichopokwenye_kiasichachakulakwawiki_9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 1 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 10 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 2 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 3 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 4 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 5 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 6 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 7 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 8 (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Total_food_price_Wiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Bei Ya Chakula Wiki 9 (Usijaze)'),
        ),
    ]
