# Generated by Django 4.2.6 on 2024-07-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_idadiyakuku_jamiiyamfugajicategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamiiyamfugajicontents',
            name='FaceBook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jamiiyamfugajicontents',
            name='Instagram',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maktabayalishecontents',
            name='Youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='matumizisahihiyaindibata',
            name='YoutubeLinkVideo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='muongozowalishe',
            name='Youtube',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
