# Generated by Django 4.2.6 on 2024-07-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_jamiiyamfugajicontents_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakundiYaVyakula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jina', models.CharField(max_length=500, verbose_name='Jina')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Makundi Ya Vyakula',
            },
        ),
        migrations.AddField(
            model_name='vyakula',
            name='CALC',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha CALC - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='CARBO',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha CARBO - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='CP',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha CP - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='FAT',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha FAT - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='LYSIN',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha LYSIN  - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='ME',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha ME - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='METH',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha METH - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='P',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha P - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='TRYPTO',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha TRYPTO - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='FoodGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.makundiyavyakula', verbose_name='Kundi La Chakula'),
        ),
    ]
