# Generated by Django 4.2.6 on 2024-07-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_taarifazakuku_cabohydrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipindiVyaKuku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kipindi', models.CharField(max_length=500, verbose_name='Kipindi')),
                ('Muda', models.CharField(default='0-2', max_length=500, verbose_name='Muda')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Makundi Ya Vyakula',
            },
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_1',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_10',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_11',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_12',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_13',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_14',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_15',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_16',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_2',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_3',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_4',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_5',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_6',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_7',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_8',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Atatumia_Kg_KwaWiki_9',
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CALC Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CARBO Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha FAT Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha LYSIN Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 10 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 11 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 12 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 13 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 14 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 15 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 16 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 2 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 3 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 4 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 5 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 6 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 7 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 8 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kinachohitajika Kwa Wiki 9 - Kca/Kg (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha P Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_10',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 10 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_11',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 11 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 12 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 13 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_14',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 14 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_15',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 15 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_16',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 16 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 2 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 3 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 4 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 5 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_6',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 6 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_7',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 7 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_8',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 8 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki_9',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha TRYPTO Kinachohitajika Kwa Wiki 9 - % (Usijaze)'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='Kipindi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vipindivyakuku', verbose_name='Kipindi'),
        ),
    ]
