# Generated by Django 4.2.6 on 2024-07-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_vipindivyakuku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='Kipindi',
        ),
    ]
