# Generated by Django 4.2.6 on 2024-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_remove_taarifazakuku_kipindi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siku', models.IntegerField(verbose_name='Siku ?')),
                ('Wiki', models.IntegerField(blank=True, null=True, verbose_name='Wiki ? (Usijaze)')),
                ('Mwezi', models.IntegerField(blank=True, null=True, verbose_name='Wiki ? (Usijaze)')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Siku',
            },
        ),
    ]
