# Generated by Django 4.2.6 on 2024-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_siku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siku',
            name='Mwezi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mwezi ? (Usijaze)'),
        ),
    ]
