# Generated by Django 4.2.6 on 2024-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_siku_mwezi'),
    ]

    operations = [
        migrations.AddField(
            model_name='umriwakuku',
            name='Interval',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interval'),
        ),
    ]
