# Generated by Django 4.2.6 on 2024-07-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_umriwakuku_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelZaWafugaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=100, verbose_name='Level Ya Mfugaji')),
                ('Nyota', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kanda')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'LevelZaWafugaji',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='AinaYaKuku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.ainazakuku', verbose_name='Aina Ya Kuku'),
        ),
        migrations.CreateModel(
            name='Mikoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaMkoa', models.CharField(max_length=100, verbose_name='Jina La Mkoa')),
                ('Kanda', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kanda')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Bei Ya Chakula')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Chakula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vyakula', verbose_name='Aina Ya Chakula')),
            ],
            options={
                'verbose_name_plural': 'Mikoa',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.levelzawafugaji', verbose_name='Level Ya Mfugaji'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='MKoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.mikoa', verbose_name='Mkoa'),
        ),
    ]
