# Generated by Django 4.2.6 on 2024-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_userrole_userstatus_rename_mkoa_myuser_mkoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainazakuku',
            name='FinisherFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finisher Feed'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='GrowerFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Grower Feed'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='LayerFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Layer Feed'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='StaterFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stater Feed'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali'),
        ),
    ]
