# Generated by Django 4.2.6 on 2024-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_mudawakumbushousafishajibanda_alter_ainazakuku_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudawakumbushousafishajibanda',
            name='EndingTime',
            field=models.TimeField(verbose_name='Muda Wa Kuisha'),
        ),
        migrations.AlterField(
            model_name='mudawakumbushousafishajibanda',
            name='StartingTime',
            field=models.TimeField(verbose_name='Muda Wa Kuanza'),
        ),
    ]
