# Generated by Django 4.2.6 on 2024-08-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_mudawakumbushousafishajibanda_endingtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AinaZaChanjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaChanjo', models.CharField(max_length=200, verbose_name='Jina La Chanjo')),
                ('Kutolewa', models.IntegerField(blank=True, null=True, verbose_name='Hutolewa Siku Ya Ngapi ?')),
                ('MaelezoYaChanjo', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Maelezo Ya Chanjo')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aina Za Chanjo',
            },
        ),
        migrations.AlterField(
            model_name='kumbushousafishajibanda',
            name='SikuZaKukumbushwa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ukumbushwe Baada Ya Siku ?'),
        ),
        migrations.CreateModel(
            name='KumbushoLaChanjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=13, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('AinaYaChanjo', models.ManyToManyField(blank=True, to='App.ainazachanjo', verbose_name='Aina Ya Chanjo')),
                ('AinaYaKuku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.ainazakuku', verbose_name='Aina Ya Kuku')),
                ('UmriWaKuku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.umriwakuku', verbose_name='Umri Wa Kuku')),
            ],
            options={
                'verbose_name_plural': 'Kumbusho La Chanjo',
            },
        ),
    ]
