# Generated by Django 4.2.6 on 2024-08-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_kumbusholauatamiajiwamayai'),
    ]

    operations = [
        migrations.CreateModel(
            name='DukaLako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kinahusiana Na ?')),
                ('Maelezo', models.TextField(max_length=10000)),
                ('LevelImage', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Nyota')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=13, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.userstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Duka Lako',
            },
        ),
    ]
