# Generated by Django 4.2.6 on 2024-08-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_remove_taarifazakuku_kiasichacalckilichopokwenye_kiasichachakulakwawiki_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaSiku',
        ),
    ]
