# Generated by Django 4.2.6 on 2024-08-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_remove_taarifazakuku_kiasichacalckilichopokwenye_kiasichachakulakwasiku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCALCKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCARBOKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaCPKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaFATKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaLYSINKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaMEKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaPKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='KiasiChaTRYPTOKilichopokwenye_KiasiChaChakulaKwaWiki',
        ),
        migrations.RemoveField(
            model_name='taarifazakuku',
            name='UmriKwaWiki',
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 10 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 11 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 12 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 13 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 14 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 15 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 16 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 17 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 18 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 19 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 1 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 20 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 21 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 22 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 23 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 24 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 2 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 3 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 4 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 5 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 6 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 7 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 8 - KG'),
        ),
        migrations.AddField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 9 - KG'),
        ),
    ]
