# Generated by Django 4.2.6 on 2024-08-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_taarifazakuku_kiasichacpkwakukuwaumriwawiki_10_kwawiki_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AinaZaNdege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AinaYaNdege', models.CharField(max_length=100, verbose_name='Aina Ya Ndege')),
                ('StaterFeed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stater Feed')),
                ('GrowerFeed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Grower Feed')),
                ('FinisherFeed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Finisher Feed')),
                ('LayerFeed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Layer Feed')),
                ('PichaYaNdege', models.ImageField(blank=True, null=True, upload_to='media/PichaZaKuku/', verbose_name='Picha Ya Ndege')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aina Za Ndege',
            },
        ),
        migrations.RemoveField(
            model_name='kumbusholauatamiajiwamayai',
            name='AinaYaKuku',
        ),
        migrations.AddField(
            model_name='dukalako',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampuni/Jina La Biashara Yako'),
        ),
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='Kifaa',
            field=models.CharField(blank=True, choices=[('Incubator', 'Incubator'), ('Ndege Mwenyew', 'Ndege')], max_length=100, null=True, verbose_name='Unatumia nini Kuatamia ?'),
        ),
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='AinaYaNdege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.ainazandege', verbose_name='Aina Ya Ndege'),
        ),
    ]
