# Generated by Django 4.2.6 on 2024-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_ainazandege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukalako',
            name='Likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Post Likes'),
        ),
        migrations.AddField(
            model_name='dukalako',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Yako'),
        ),
        migrations.AlterField(
            model_name='dukalako',
            name='LevelImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Nyota'),
        ),
        migrations.AlterField(
            model_name='kumbusholauatamiajiwamayai',
            name='Kifaa',
            field=models.CharField(blank=True, choices=[('Incubator', 'Incubator'), ('Ndege Mwenyewe', 'Ndege Mwenyewe')], max_length=100, null=True, verbose_name='Unatumia nini Kuatamia ?'),
        ),
    ]
