# Generated by Django 4.2.6 on 2024-08-08 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_dukalako_pichayapost_dukalako_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukalako',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_dukalako', to=settings.AUTH_USER_MODEL),
        ),
    ]
