# Generated by Django 4.2.6 on 2024-08-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_alter_dukalako_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maoni', models.TextField(max_length=10000)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=13, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampuni/Jina La Biashara Yako')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Yako')),
                ('LevelImage', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Nyota')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Maoni',
            },
        ),
    ]
