# Generated by Django 4.2.6 on 2024-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_maoni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyakula',
            name='CALC',
        ),
        migrations.RemoveField(
            model_name='vyakula',
            name='CARBO',
        ),
        migrations.RemoveField(
            model_name='vyakula',
            name='FAT',
        ),
        migrations.RemoveField(
            model_name='vyakula',
            name='LYSIN',
        ),
        migrations.RemoveField(
            model_name='vyakula',
            name='P',
        ),
        migrations.RemoveField(
            model_name='vyakula',
            name='TRYPTO',
        ),
        migrations.AddField(
            model_name='vyakula',
            name='Chumvi',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chumvi - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='DCP',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha DCP - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='Mafuta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Mafuta - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='PREMIX',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha PREMIX - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='TotalPercentageRequired',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chakula Kwenye Mchanganyiko Wa Jumla Wa Chakula - %'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='Tryptophan',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Tryptophan - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='UngaWaMifupa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha UngaWaMifupa - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='Wanga',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Wanga - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AddField(
            model_name='vyakula',
            name='Lysin',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Lysin  - % Kwenye 1Kg Ya Chakula'),
        ),
    ]
