# Generated by Django 4.2.6 on 2024-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_vyakulaorder_totalfoodmixerpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdadiYaKilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdadiYaKilos', models.IntegerField(verbose_name='Idadi Ya Kilos')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Idadi Ya Kilos',
            },
        ),
        migrations.AlterField(
            model_name='idadiyakuku',
            name='IdadiYaKuku',
            field=models.IntegerField(verbose_name='Idadi Ya Kuku'),
        ),
    ]
