# Generated by Django 4.2.6 on 2024-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_remove_kumbusholachanjo_umriwakuku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaCPKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha CP Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 10 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 11 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 12 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 13 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 14 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 15 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 16 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 17 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 18 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 19 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 1 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 20 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 21 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 22 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 23 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 24 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 2 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 3 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 4 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 5 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 6 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 7 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 8 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChakulaKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chakula Kwa Wiki Kwa Kuku wa Wiki 9 - KG'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaChumviKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Chumvi Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaDCPKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha DCP Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaLysinKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Lysin Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 10 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 11 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 12 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 13 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 14 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 15 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 16 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 17 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 18 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 19 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 1 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 20 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 21 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 22 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 23 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 24 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 2 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 3 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 4 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 5 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 6 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 7 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 8 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMEKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha ME Kwa Wiki Kwa Kuku wa Wiki 9 - Kcal/kg'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMETHKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha METH Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaMafutaKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Mafuta Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaPREMIXKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha PREMIX Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaTryptophanKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Tryptophan Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaUngaWaMifupaKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha UngaWaMifupa Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_10_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 10 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_11_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 11 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_12_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 12 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_13_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 13 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_14_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 14 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_15_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 15 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_16_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 16 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_17_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 17 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_18_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 18 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_19_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 19 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_1_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 1 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_20_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 20 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_21_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 21 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_22_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 22 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_23_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 23 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_24_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 24 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_2_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 2 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_3_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 3 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_4_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 4 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_5_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 5 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_6_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 6 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_7_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 7 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_8_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 8 - %'),
        ),
        migrations.AlterField(
            model_name='taarifazakuku',
            name='KiasiChaWangaKwaKukuWaUmriWaWiki_9_KwaWiki',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Wanga Kwa Wiki Kwa Kuku wa Wiki 9 - %'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='CP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha CP - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='Chumvi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chumvi - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='DCP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha DCP - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='Lysin',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Lysin  - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='ME',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha ME - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='METH',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha METH - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='Mafuta',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Mafuta - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='PREMIX',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha PREMIX - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='ProductQuantity',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Kiasi - KG (Usijaze)'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='TotalPercentageRequired_Finisher',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chakula Kwenye Mchanganyiko Wa Jumla Wa Chakula Cha Finisher - %'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='TotalPercentageRequired_Grower',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chakula Kwenye Mchanganyiko Wa Jumla Wa Chakula Cha Grower - %'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='TotalPercentageRequired_Layer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chakula Kwenye Mchanganyiko Wa Jumla Wa Chakula Cha Layer - %'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='TotalPercentageRequired_Starter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Chakula Kwenye Mchanganyiko Wa Jumla Wa Chakula Cha Starter - %'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='Tryptophan',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Tryptophan - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='UngaWaMifupa',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha UngaWaMifupa - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='Wanga',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Wanga - % Kwenye 1Kg Ya Chakula'),
        ),
        migrations.AlterField(
            model_name='vyakula',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Bei Ya sasa Ya Chakula (Usijaze)'),
        ),
    ]
