# Generated by Django 4.2.6 on 2024-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_alter_taarifazakuku_kiasichacpkwakukuwaumriwawiki_10_kwawiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalCPPercentageRequired_Starter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha CP Kwenye Kipindi  Cha Starter - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalMafutaPercentageRequired_Starter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Mafuta Kwenye Kipindi  Cha Starter - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalWangaPercentageRequired_Starter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Wanga Kwenye Kipindi  Cha Starter - %'),
        ),
        migrations.AddField(
            model_name='dukalako',
            name='PichaYaPost2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 2'),
        ),
        migrations.AddField(
            model_name='dukalako',
            name='PichaYaPost3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 3'),
        ),
        migrations.AddField(
            model_name='dukalako',
            name='PichaYaPost4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 4'),
        ),
        migrations.AddField(
            model_name='dukalako',
            name='PichaYaPost5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 5'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='OmbaNyota',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='PichaYaLeseni',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Leseni'),
        ),
    ]
