# Generated by Django 4.2.6 on 2024-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_ainazakuku_totalcppercentagerequired_starter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholachanjo',
            name='UmriWaKukuKwaSiku',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Umri Wa Kuku Kwa Siku'),
        ),
        migrations.AddField(
            model_name='kumbusholachanjo',
            name='UmriWaKukuKwaWiki',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Umri Wa Kuku Kwa Wiki'),
        ),
    ]
