# Generated by Django 4.2.6 on 2024-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_kumbusholachanjo_umriwakukukwasiku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalCPPercentageRequired_Finisher',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha CP Kwenye Kipindi  Cha Finisher - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalCPPercentageRequired_Grower',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha CP Kwenye Kipindi  Cha Grower - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalCPPercentageRequired_Layer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha CP Kwenye Kipindi  Cha Layer - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalMafutaPercentageRequired_Finisher',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Mafuta Kwenye Kipindi  Cha Finisher - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalMafutaPercentageRequired_Grower',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Mafuta Kwenye Kipindi  Cha Grower - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalMafutaPercentageRequired_Layer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Mafuta Kwenye Kipindi  Cha Layer - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalWangaPercentageRequired_Finisher',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Wanga Kwenye Kipindi  Cha Finisher - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalWangaPercentageRequired_Grower',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Wanga Kwenye Kipindi  Cha Grower - %'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='TotalWangaPercentageRequired_Layer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kiwango Cha Jumla Cha Wanga Kwenye Kipindi  Cha Layer - %'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='TotalFoodAmount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya  Kiasi Cha Chakula - Kg'),
        ),
    ]
