# Generated by Django 4.2.6 on 2024-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_remove_taarifazakuku_kiasichacpkwakukuwaumriwawiki_10_kwawiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukalako',
            name='UserRole',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Aina Ya Mtumiaji'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='TotalConstantFoodMixerPercentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Percentage Ya Vyakula Vyote (constant Food) - %'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='TotalMixerKios_ForConstantFoodGroups',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Kiasi Ya Vyakula Vyote Vilivyochagualiwa kutoka kwenye (constant Food Groups) - Kg'),
        ),
        migrations.AlterField(
            model_name='dukalako',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili'),
        ),
        migrations.AlterField(
            model_name='kumbusholachanjo',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili'),
        ),
        migrations.AlterField(
            model_name='kumbusholauatamiajiwamayai',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili'),
        ),
        migrations.AlterField(
            model_name='kumbushousafishajibanda',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalFoodMixerPercentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Percentage Ya Vyakula Vyote (Variables Food) - %'),
        ),
    ]
