# Generated by Django 4.2.6 on 2024-08-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_dukalako_userrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vyakulaorder',
            name='AinaYaKuku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aina Ya Kuku'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='FinisherFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finisher Feed'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='GrowerFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Grower Feed'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='LayerFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Layer Feed'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='StaterFeed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stater Feed'),
        ),
        migrations.AddField(
            model_name='vyakulaorder',
            name='UmriKwaSiku',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Umri Wa Kuku Kwa Siku'),
        ),
    ]
