# Generated by Django 4.2.6 on 2024-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_vyakulaorder_ainayakuku_vyakulaorder_finisherfeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalConstantFoodMixerPercentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya Percentage Ya Vyakula Vyote (constant Food) - %'),
        ),
    ]
