# Generated by Django 4.2.6 on 2024-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_alter_vyakulaorder_totalconstantfoodmixerpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalCPPercentageRequired',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya  Kiasi Cha CP Kwenye Chakula - %'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalFoodAmount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya  Kiasi Cha Chakula - Kg'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalFoodMixerPercentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya Percentage Ya Vyakula Vyote (Variables Food) - %'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalMafutaPercentageRequired',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya  Kiasi Cha Mafuta Kwenye Chakula - %'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalMixerKios_ForConstantFoodGroups',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya Kiasi Ya Vyakula Vyote Vilivyochagualiwa kutoka kwenye (constant Food Groups) - Kg'),
        ),
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalWangaPercentageRequired',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jumla Ya  Kiasi Cha Wanga Kwenye Chakula - %'),
        ),
    ]
