# Generated by Django 4.2.6 on 2024-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0058_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aliye Like Ni: '),
        ),
    ]
