# Generated by Django 4.2.6 on 2024-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_notification_photo_notification_postowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='SikuKamiliZaKuatamia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siku Zake kamili za Ndege Kuatamia'),
        ),
        migrations.AlterField(
            model_name='kumbusholauatamiajiwamayai',
            name='AinaYaNdege',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Aina Ya Ndege'),
        ),
    ]
