# Generated by Django 4.2.6 on 2024-08-30 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0062_kumbusholauatamiajiwamayai_sikukamilizakuatamia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainazandege',
            name='SikuKamiliZaKuatamia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siku Kamili Za Kuatamia'),
        ),
        migrations.AddField(
            model_name='notification',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali Anapoishi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='Maelezo',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='PichaYaPost',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='PichaYaPost2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 2'),
        ),
        migrations.AddField(
            model_name='notification',
            name='PichaYaPost3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 3'),
        ),
        migrations.AddField(
            model_name='notification',
            name='PichaYaPost4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 4'),
        ),
        migrations.AddField(
            model_name='notification',
            name='PichaYaPost5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Post 5'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yake'),
        ),
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yake ya Simu'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
