# Generated by Django 4.2.6 on 2024-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0063_ainazandege_sikukamilizakuatamia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbushousafishajibanda',
            name='day_is_reached',
            field=models.BooleanField(default=False),
        ),
    ]
