# Generated by Django 4.2.6 on 2024-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_kumbushousafishajibanda_message_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbushousafishajibanda',
            name='SikuZaKukumbushwaDisplayedValue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ukumbushwe Baada Ya Siku (TunayotumiaKudisplay- Usijaze) ?'),
        ),
    ]
