# Generated by Django 4.2.6 on 2024-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_kumbushousafishajibanda_sikuzakukumbushwadisplayedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='day_is_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='message_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
