# Generated by Django 4.2.6 on 2024-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0067_kumbusholauatamiajiwamayai_day_is_reached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholauatamiajiwamayai',
            name='SikuKamiliZaKuatamiaDisplayed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Siku Zake kamili za Ndege Kuatamia (TunayotumiaKudisplay -Usijaze)'),
        ),
    ]
