# Generated by Django 4.2.6 on 2024-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0070_alter_emailsendcount_kumbusholauatamiajiwamayai_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholachanjo',
            name='day_is_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kumbusholachanjo',
            name='message_is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='company name'),
        ),
    ]
