# Generated by Django 4.2.6 on 2024-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0071_kumbusholachanjo_day_is_reached_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KumbushoLaMabadilikoYaLishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LengoLaKufuga', models.CharField(blank=True, choices=[('Nafuga kwa ajili ya mayai', 'Nafuga kwa ajili ya mayai'), ('Nafuga kwa ajili ya nyama', 'Nafuga kwa ajili ya nyama')], max_length=500, null=True, verbose_name='Lengo La Kufuga Hao Kuku ?')),
                ('KundiLaKukuWake', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kundi La Kuku Wake')),
                ('AinaYaKuku', models.CharField(blank=True, max_length=500, null=True, verbose_name='Aina Ya Kuku')),
                ('UmriWaKukuKwaSiku', models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Siku')),
                ('UmriWaKukuKwaWiki', models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Wiki')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kumbusho La Mabadiliko Ya Lishe',
            },
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Status',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Tick',
            field=models.CharField(blank=True, choices=[('Ndio Anastahili', 'Ndio Anastahili'), ('Hapana Hastahili', 'Hapana Hastahili')], max_length=100, null=True, verbose_name='Anastahili Tiki ?'),
        ),
    ]
