# Generated by Django 4.2.6 on 2024-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0072_kumbusholamabadilikoyalishe_remove_myuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukalako',
            name='TickStatus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tick Status'),
        ),
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='MfumoWaKufuga',
            field=models.CharField(blank=True, choices=[('Shadidi (mfumo wa ndani tu)', 'Shadidi (mfumo wa ndani tu)'), ('Nusu huria (mfumo wa ndani na nje)', 'Nusu huria (ndani na nje)'), ('Huria (mfumo wa nje)', 'Huria (mfumo wa nje)')], max_length=500, null=True, verbose_name='Mfumo Wa Kufuga Unaotumia ?'),
        ),
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='MudaWaKumbusho',
            field=models.CharField(blank=True, choices=[('12:00 asubuhi -> 6:00 mchana', '12:00 asubuhi -> 6:00 mchana'), ('6:00 mchana -> 12:00 jioni', '6:00 mchana -> 12:00 jioni')], max_length=500, null=True, verbose_name='Muda Wa Kukumbushwa ?'),
        ),
    ]
