# Generated by Django 4.2.6 on 2024-09-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0073_dukalako_tickstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='day_is_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='message_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
