# Generated by Django 4.2.6 on 2024-09-08 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0074_kumbusholamabadilikoyalishe_day_is_reached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='UmriWaKukuKwaSiku_KwaMahesabuTu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Siku Kwa Mahesabu Tu'),
        ),
        migrations.AddField(
            model_name='kumbusholamabadilikoyalishe',
            name='UmriWaKukuKwaWiki_KwaMahesabuTu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Wiki Kwa Mahesabu Tu'),
        ),
        migrations.CreateModel(
            name='EmailSendCount_KumbushoLaMabadilikoYaLishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Count Kumbusho La Mabadiliko Ya Lishe',
            },
        ),
    ]
