# Generated by Django 4.2.6 on 2024-09-10 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0076_emailsendcount_kumbusholachanjo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumbusholamabadilikoyalishe',
            name='LengoLaKufuga',
            field=models.CharField(blank=True, choices=[('Kwaajili Ya Mayai', 'Kwaajili Ya Mayai'), ('Kwaajili Ya Nyama', 'Kwaajili Ya Nyama')], max_length=500, null=True, verbose_name='Lengo La Kufuga Hao Kuku ?'),
        ),
        migrations.CreateModel(
            name='EmailSendCount_DukaLako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Count Duka Lako',
            },
        ),
    ]
