# Generated by Django 4.2.6 on 2024-09-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0077_alter_kumbusholamabadilikoyalishe_lengolakufuga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendcount_dukalako',
            name='ApprovedMaelezoPost',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Maelezo Ya Posti Aliyohakiki'),
        ),
        migrations.AddField(
            model_name='emailsendcount_dukalako',
            name='ApprovedPost',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Posti Aliyohakiki'),
        ),
    ]
