# Generated by Django 4.2.6 on 2024-09-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0080_maoni_is_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maoni',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jina Lako Kamili'),
        ),
        migrations.CreateModel(
            name='Wanunuzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampuni/Jina La Biashara Yako')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Yako')),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.mikoa', verbose_name='Mkoa')),
            ],
            options={
                'verbose_name_plural': 'Wanunuzi',
            },
        ),
    ]
