# Generated by Django 4.2.6 on 2024-09-11 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0081_alter_maoni_username_wanunuzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanunuzi',
            name='Message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='EmailSendCount_Wanunuzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Yako ya Simu')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Lako Kamili')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mahali')),
                ('JinaLaMnunuzi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina La Mnunuzi')),
                ('NambaYaSimuYaMnunuzi', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Ya Simu Ya Mnunuzi')),
                ('Mkoa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mkoa')),
                ('Wilaya', models.CharField(blank=True, max_length=500, null=True, verbose_name='Wilaya')),
                ('last_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Count Kumbusho Wanunuzi',
            },
        ),
    ]
